*** Settings ***


*** Variables ***
#URL
${BASE_URL}                        https://reqres.in

#AUTENTICATION
${EP_LOGIN}                        /api/login

#USERS
${EP_LIST_USERS}                   /api/users
${EP_USER}                         /api/users/
${EP_USER_REGISTER}                /api/register
${EP_USER_UPDATE}                  /api/users/  
${EP_USER_DELETE}                  /api/users/
